services:
  pocketbase:
    build: ./backend
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/pb_data:/pb_data
      - ./backend/pb_public:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports: 
      - "3000:3000"
    